name: Workflow Inputs
on: 
  workflow_dispatch:
    inputs:
      boolean_required_default_false:
        description: "Choose a value for this required boolean, default: false"
        type: boolean
        default: false
        required: true
      boolean_optional_default_true:
        description: "Choose a value for this optional boolean, default: true"
        type: boolean
        default: true
        required: false
      project:
        description: "Select which project you want to run the workflow for"
        type: choice
        options:
          - project1
          - project2
      workflow_tag:
        description: Tag to use on workflow title
        type: string
        default: "no name"
        required: true
      number_input:
        description: "A number. Magic number for test to pass is 5"
        type: number
        default: 0
        required: true
      environment_var:
        type: environment

run-name: "${{ inputs.workflow_tag }} with options: boolean_required: ${{ inputs.boolean_required_default_false }}, boolean_optional: ${{ inputs.boolean_optional_default_true }}, project: ${{ inputs.project }}, by ${{ github.actor }}"
jobs:
  log_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        run: echo "${{ toJson(github.event.inputs) }}"
      - name: Check magic number
        if: inputs.number_input != 5
        run: exit 1
      - name: Check magic number version 2
        run: |
         if [[ "${{ inputs.number_input }}" != "5" ]]; then
          echo "::error::Expected 5, got ${{ inputs.number_input }}"
          exit 1
         fi
